#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Package-Stash
Version  : 0.39
Release  : 22
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-0.39.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-0.39.tar.gz
Summary  : 'Routines for manipulating stashes'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Package-Stash-bin = %{version}-%{release}
Requires: perl-Package-Stash-perl = %{version}-%{release}
Requires: perl(Dist::CheckConflicts)
BuildRequires : buildreq-cpan
BuildRequires : perl(CPAN::Meta::Check)
BuildRequires : perl(Dist::CheckConflicts)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Needs)
BuildRequires : perl(Try::Tiny)

%description
This archive contains the distribution Package-Stash,
version 0.39:
Routines for manipulating stashes

%package bin
Summary: bin components for the perl-Package-Stash package.
Group: Binaries

%description bin
bin components for the perl-Package-Stash package.


%package dev
Summary: dev components for the perl-Package-Stash package.
Group: Development
Requires: perl-Package-Stash-bin = %{version}-%{release}
Provides: perl-Package-Stash-devel = %{version}-%{release}
Requires: perl-Package-Stash = %{version}-%{release}

%description dev
dev components for the perl-Package-Stash package.


%package perl
Summary: perl components for the perl-Package-Stash package.
Group: Default
Requires: perl-Package-Stash = %{version}-%{release}

%description perl
perl components for the perl-Package-Stash package.


%prep
%setup -q -n Package-Stash-0.39
cd %{_builddir}/Package-Stash-0.39

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/package-stash-conflicts

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Package::Stash.3
/usr/share/man/man3/Package::Stash::PP.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.3/Package/Stash.pm
/usr/lib/perl5/vendor_perl/5.30.3/Package/Stash/Conflicts.pm
/usr/lib/perl5/vendor_perl/5.30.3/Package/Stash/PP.pm
