#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Package-Stash
Version  : 0.37
Release  : 2
URL      : http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Package-Stash-0.37.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Package-Stash-0.37.tar.gz
Summary  : 'routines for manipulating stashes'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-Package-Stash-bin
Requires: perl-Package-Stash-doc
BuildRequires : perl(Dist::CheckConflicts)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Requires)
BuildRequires : perl(Try::Tiny)

%description
This archive contains the distribution Package-Stash,
version 0.37:
routines for manipulating stashes

%package bin
Summary: bin components for the perl-Package-Stash package.
Group: Binaries

%description bin
bin components for the perl-Package-Stash package.


%package doc
Summary: doc components for the perl-Package-Stash package.
Group: Documentation

%description doc
doc components for the perl-Package-Stash package.


%prep
%setup -q -n Package-Stash-0.37

%build
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.24.0/Package/Stash.pm
/usr/lib/perl5/site_perl/5.24.0/Package/Stash/Conflicts.pm
/usr/lib/perl5/site_perl/5.24.0/Package/Stash/PP.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/package-stash-conflicts

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
