#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Package-Stash
Version  : 0.40
Release  : 35
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-0.40.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-0.40.tar.gz
Summary  : 'Routines for manipulating stashes'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Package-Stash-bin = %{version}-%{release}
Requires: perl-Package-Stash-license = %{version}-%{release}
Requires: perl-Package-Stash-perl = %{version}-%{release}
Requires: perl(Dist::CheckConflicts)
BuildRequires : buildreq-cpan
BuildRequires : perl(CPAN::Meta::Check)
BuildRequires : perl(Dist::CheckConflicts)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Needs)
BuildRequires : perl(Try::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution Package-Stash,
version 0.40:
Routines for manipulating stashes

%package bin
Summary: bin components for the perl-Package-Stash package.
Group: Binaries
Requires: perl-Package-Stash-license = %{version}-%{release}

%description bin
bin components for the perl-Package-Stash package.


%package dev
Summary: dev components for the perl-Package-Stash package.
Group: Development
Requires: perl-Package-Stash-bin = %{version}-%{release}
Provides: perl-Package-Stash-devel = %{version}-%{release}
Requires: perl-Package-Stash = %{version}-%{release}

%description dev
dev components for the perl-Package-Stash package.


%package license
Summary: license components for the perl-Package-Stash package.
Group: Default

%description license
license components for the perl-Package-Stash package.


%package perl
Summary: perl components for the perl-Package-Stash package.
Group: Default
Requires: perl-Package-Stash = %{version}-%{release}

%description perl
perl components for the perl-Package-Stash package.


%prep
%setup -q -n Package-Stash-0.40
cd %{_builddir}/Package-Stash-0.40

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Package-Stash
cp %{_builddir}/Package-Stash-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Package-Stash/da781ad4cfead0df917de25fe475c39b124364ab || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/package-stash-conflicts

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Package::Stash.3
/usr/share/man/man3/Package::Stash::PP.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Package-Stash/da781ad4cfead0df917de25fe475c39b124364ab

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
